sudo: false

language: go

go:
  - 1.6
  - tip

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover
  - npm install codeclimate-test-reporter
  # Workaround for travis
  # - go get -t -v ./...

addons:
  code_climate:
    repo_token:
      # CODECLIMATE_REPO_TOKEN
      secure: "MZDZD0/uo6G99JWqp0K5mS1S8CXN3ceAZIYxxBG3LdYWGZXJ9tcicwlkfT4yY28Bc61JbLQ+VjKJkjjBMTnTRDtTp/Wsy7Yl1xyzB7GSwjLvwn+VM9UmjexY8Q6QL6EQBzt3zO4ukBfUIqUa7WB+E4fQVY0/QLQlQ6IRUvqTUtWbISSJjhPbq7UvjmNQ+/xrX+IKwJD1lQDNr3263eWxSgGzSJluhH9lUZ3sNIGlchzrxs2+158uzXmdiDK29xi8XlZtjOwaAxUHS0e91+2oyUd8BeriLttBfN+YYYbSryr3B90T4zkDNdq2XsilxZE+b25jCmHPyrEHEeMy1BIiYWDGdZXKLBWbgFVIudzhcsrXqk43JtH2o+BhN+v1fp7+YXRPd2ARlBKBC6ElJ9Yukws69C6kJCky6E0IAH+L89i1E7YU92PWHkcuEss75HaPlxIR5cJS8w/s0kqqooBWhZn4hT5UhBu9SEnLiHbVm5Q8Ero/2rKGLvLltq/dFJHNMhrQTrwLrO+OEJ8U7cMowo+RcVXOkPkID75UFiKQ21v0H9WeKoLGlrBiKZ2kcv3NFI25Ax4VryLdFrZcN9XxcyhSLEk8XoQjIdZHvIe/i5bvQaKlKzD2LiGqv8olYi6JTg6F8A8o/v/B+jB3w6zpf4m9na/gJx26rVhqW8sBruo="

script:
  - go vet -x  $(go list ./... | grep -v /vendor/)
  - go test -race --coverprofile=mqtt.coverprofile ./mqtt
  - go test -race --coverprofile=packet.coverprofile ./mqtt/packet

after_script:
  - gover
  - codeclimate-test-reporter < gover.coverprofile
